title: NeurIPS 2024 Workshop on Generative AI and Creativity
description: A dialogue between machine learning researchers and creative professionals
show_downloads: False
google_analytics:
theme: jekyll-theme-cayman
